server:
  port: 8080
  forward-headers-strategy: framework
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aumigos_dev
    username: aumigos
    password: aumigos
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring.security.user:
  name: admin
  password: admin123

oci:
  objectstorage:
    namespace: grrb8txifgz9
    bucket: aumigos-uploads

