server:
  forward-headers-strategy: framework
  compression:
    enabled: true

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
