server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aumigos_dev
    username: aumigos
    password: aumigos
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

logging:
  level:
    root: info
