server:
  forward-headers-strategy: framework
  compression:
    enabled: true

spring:
  jackson:
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-properties: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: sa-saopaulo-1
        auto: false
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        endpoint: "https://${S3_NAMESPACE}.compat.objectstorage.sa-saopaulo-1.oraclecloud.com"
        path-style-access: true
        bucket: ${S3_BUCKET:aumigos-uploads}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
