name: Build & Push Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR (Gradle)
        run: |
          chmod +x ./gradlew || true
          ./gradlew -Dorg.gradle.daemon=false -x test bootJar
          ls -lh build/libs

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (runtime Dockerfile)
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/ong-backend
          TAG=${{ github.sha }}
          docker build -f Dockerfile.ci -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
